version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - local
    restart: always
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh 0.0.0.0:${MONGO_PORT}/ --quiet"
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s

  todo-app:
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    env_file:
      - .env
    environment:
      MONGO_HOST: "mongodb"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - local
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    expose:
      - ${APP_PORT}
    entrypoint:
      - node
    command: 
      - dist/main/main.js

networks:
  local:
    name: local
    driver: bridge